alias fvisit='/Applications/VisIt.app/Contents/MacOS/VisIt -assume_format FLASH'
alias ompirun='mpirun --oversubscribe'
alias sshAX='ssh acreyes@asterix.uchicago.edu'
alias sshDL='ssh areyes@cl7head'
alias sshBH='ssh areyes14@bluehive.circ.rochester.edu'
alias sshFL='ssh acreyes@flash.rochester.edu'

alias amrvis1d='/Users/adamreyes/Documents/research/repos/github/Amrvis/amrvis1d.gnu.ex'
alias amrvis2d='/Users/adamreyes/Documents/research/repos/github/Amrvis/amrvis2d.gnu.ex'
alias amrvis3d='/Users/adamreyes/Documents/research/repos/github/Amrvis/amrvis3d.gnu.ex'
